export const ADD_TODO = 'ADD_TODO';
export const MARK_COMPLETED = 'MARK_COMPLETED';
export const CHANGE_TASK_TEXT = 'CHANGE_TASK_TEXT';
export const ADD_SUBTASK = 'ADD_SUBTASK';
export const CHANGE_SUBTASK_TEXT = 'CHANGE_SUBTASK_TEXT';
